# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 441d095eda34b49718f775d53faaadea96479ce2c64fc0269a7dfd9096fb188e8be48de188828f2798d0830f6cc625bef8a76953be67a3b80ceb5a50d23b434d

test:
  secret_key_base: dadfec2f067726ea5be82ddd5c022f9778d13010d7f16efd918853884e1603455a0f974becef184ed0ed5398bd3d265595b6b9cbd1ff4d7d1611f27db63ecc23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
